version: '3.8'

services:
  api:
    container_name: LibreChat
    ports:
      - 3080:3080
    depends_on:
      - mongodb
      - rag_api
    # image: ghcr.io/danny-avila/librechat:latest
    build: .
    restart: always
    user: "1000:1000"
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}

      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CREDS_KEY=${CREDS_KEY}
      - CREDS_IV=${CREDS_IV}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION}
    volumes:
      - images:/app/client/public/images
      - uploads:/app/uploads
      - logs:/app/api/logs
      - E:\librechat\librechat.yaml:/app/librechat.yaml:ro


  mongodb:
    container_name: chat-mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    command: mongod --noauth

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - meili_data:/meili_data

  vectordb:
    container_name: vectordb
    image: ankane/pgvector:latest
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-mydatabase}
      - POSTGRES_USER=${POSTGRES_USER:-myuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata2:/var/lib/postgresql/data

  rag_api:
    container_name: rag_api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    restart: always
    depends_on:
      - vectordb
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}

      - POSTGRES_HOST=vectordb
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL}

volumes:
  images:
  uploads:
  logs:
  mongodb_data:
  meili_data:
  pgdata2:
